"""initial migration

Revision ID: d0d392b34db2
Revises: 
Create Date: 2020-10-14 22:49:31.292975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d392b34db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('figi'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('price_candle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('price_open', sa.Float(), nullable=False),
    sa.Column('price_close', sa.Float(), nullable=False),
    sa.Column('price_max', sa.Float(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=False),
    sa.Column('financial_instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_instrument_id'], ['financial_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('datetime_from', sa.DateTime(), nullable=False),
    sa.Column('datetime_to', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('hold_profit', sa.Float(), nullable=False),
    sa.Column('strategy_profit', sa.Float(), nullable=False),
    sa.Column('financial_instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_instrument_id'], ['financial_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_report')
    op.drop_table('price_candle')
    op.drop_table('financial_instrument')
    # ### end Alembic commands ###
